name: ppinsight
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - altair
  - requests
  - Biopython
  - pytest
  - pytest-cov
prefix: /home/mayagh/miniforge3
