name: ppinsight
channels:
  - conda-forge
  - bioconda
  - defaults
  - pip
dependencies:
  - python=3.11
  # vvv modern numpy compatible with many packages
  - numpy>=1.24
  - pandas
  # vvv avoids very old matplotlib builds; conda-forge will provide compatible binaries
  - matplotlib>=3.6
  - altair
  - requests
  - biopython
  - pytest
  - pytest-cov
  - ruff
  - mpi4py
  - zlib
  - haddock_biobb
  - pip
  - pip:
    - lightdock
    - pyrosetta-installer