name: ppinsight
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - altair
  - requests
  - Biopython
  - pytest
  - pytest-cov
  - ruff
  - mpi4py
  - zlib
  - haddock_biobb
  - pip
  - pip:
    - lightdock